table Time
	lineageTag: e1a443bc-196c-493c-adc4-046c13696cbd
	dataCategory: Time

	column ReportingPeriodID
		dataType: int64
		lineageTag: 40cb4012-ef03-40be-8a7f-3ee144e390b6
		summarizeBy: none
		sourceColumn: ReportingPeriodID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period
		dataType: int64
		lineageTag: 913292a8-3234-4e8f-ba37-eaa2e6e00256
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FiscalYear
		dataType: int64
		lineageTag: 761427c4-b799-4602-92a8-534888d28f13
		dataCategory: Year
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FiscalMonth
		dataType: string
		lineageTag: a1e966ab-7223-4c55-9ff0-1f14046a437d
		dataCategory: Month
		summarizeBy: none
		sourceColumn: FiscalMonth
		sortByColumn: Period

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		isKey
		formatString: m/d/yy
		lineageTag: bac47cf7-f718-4f8d-a8e7-64a33a730db7
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition Time = m
		mode: import
		source =
				let
				    Source = Sql.Database(".", "RetailBIDW", [Query="select distinct#(lf)concat(year(dateadd(year, 2, [BusinessDayDate] )),RIGHT('0'+cast(month(dateadd(year, 2, [BusinessDayDate] )) as varchar(2)), 2), RIGHT('0'+cast(day(dateadd(year, 2, [BusinessDayDate] )) as varchar(2)), 2) ) ReportingPeriodID, #(lf)  month(dateadd(year, 2, [BusinessDayDate] )) Period, #(lf)  left(DATENAME(month, dateadd(year, 2, [BusinessDayDate] )), 3) FiscalMonth, #(lf)  year(dateadd(year, 2, [BusinessDayDate] ) ) FiscalYear, #(lf)  dateadd(year, 2, [BusinessDayDate] ) [BusinessDayDate]#(lf)from [Time_Dimension]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"ReportingPeriodID", "ReportingPeriodID"}, {"Period", "Period"}, {"FiscalYear", "FiscalYear"}, {"FiscalMonth", "FiscalMonth"}, {"BusinessDayDate", "Month"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ReportingPeriodID", Int64.Type}, {"Period", Int64.Type}, {"FiscalYear", Int64.Type}, {"FiscalMonth", type text}, {"Month", type datetime}})
				in
				    #"Changed Type"

